name: Deploy React app

on:
  push:
    branches:
      - main

env:
  VITE_API_URL: "www.mittapi.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/where-its-at:latest